<?php
/**
 * @file capkopper_corporate.install
 * Install, update and uninstall functions.
 */

/**
 * Implements hook_install().
 */
function capkopper_corporate_install() {
  // Set the default theme.
  _capkopper_corporate_set_up_theme();
}

/**
 * Set the default theme.
 */
function _capkopper_corporate_set_up_theme() {
  $theme = 'responsive_bartik';
  theme_enable(array($theme));
  variable_set('theme_default', $theme);
  theme_disable(array('bartik'));
}
